# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.FileField(default=datetime.datetime(2017, 5, 17, 17, 59, 37, 415031, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
